use_frameworks!

target 'NaturalKorean_Example' do
  pod 'NaturalKorean', :path => '../'
  
  target 'NaturalKorean_ExampleTests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

