use_frameworks!

target 'NaturalKorean_Example' do
  pod 'NaturalKorean', :path => '../'

  target 'NaturalKorean_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
